### ISSUE TITLE
Bug with RadialStatus

### ISSUE THREAD

**Issue by sitiom** [Discord-Theme-Addons/amazing-activity-cards#3]
Broke with the latest commit (https://github.com/Discord-Theme-Addons/amazing-activity-cards/commit/592fbdf55cd2e79d6bf0f01c2a7656d1fabca46c):
![image](https://user-images.githubusercontent.com/56180050/115979880-1386c980-a5bb-11eb-88d2-8246aba4e878.png)

**Comment by LuckFire** [comment]
should be fixed now
